### ISSUE TITLE
Race Condition while retrieving ETA?

### ISSUE THREAD

**Issue by stefan2904** [realraum/Limnoria-RealRaum#17]
```
(21:58:15) nicoo: !food
(21:58:21) r3bot: nicoo: An error has occurred and has been logged. Please contact this bot's administrator for more information.
```

=>

```
INFO 2015-09-07T21:58:15 supybot food called on #realraum by "nicoo!~nico@nicoo.user.oftc.net".
ERROR 2015-09-07T21:58:20 supybot Uncaught exception in ['food'].
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/supybot/callbacks.py", line 1280, in _callCommand
    self.callCommand(command, irc, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/utils/python.py", line 91, in g
    f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/callbacks.py", line 1261, in callCommand
    method(irc, msg, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/supybot/commands.py", line 1079, in newf
    f(self, irc, msg, args, *state.args, **state.kwargs)
  File "/home/pi/runbot/plugins/RealRaum/plugin.py", line 113, in food
    "Order already submitted. ETA: " + self.mjam.loadOrderETA())
  File "/home/pi/runbot/plugins/RealRaum/mjam.py", line 54, in loadOrderETA
    self.order_eta = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
ERROR 2015-09-07T21:58:20 supybot Exception id: 0xa5058
INFO 2015-09-07T21:58:54 supybot food called on #realraum by "realraum!~realraum@wuerfel.realraum.at".
```

**Comment by stefan2904** [comment]
(thanks to @nbraud for "reporting")
